default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  url: postgresql://ror6:mydbpassword@postgres:5432/testdb

template: &template
  adapter: postgresql
  pool: 5
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV['DATABASE_PORT'] %>
  database: <%= ENV['PRODUCTION_DATABASE'] %>
  username: <%= ENV['DATABASE_USERNAME'] %> 
  password: <%= ENV['DATABASE_PASSWORD'] %>
  timeout: 5000
  
production:
  <<: *template
  pool: 10